
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int GREATERTHAN = 47;
  public static final int CHAR_TYPE = 6;
  public static final int DIVIDE = 30;
  public static final int BOOL_TYPE = 2;
  public static final int POWER = 31;
  public static final int CHAR = 53;
  public static final int CONCAT = 38;
  public static final int POOL = 11;
  public static final int NOTEQUAL = 35;
  public static final int LPAREN = 39;
  public static final int INT = 54;
  public static final int MINUS = 28;
  public static final int RAT_TYPE = 4;
  public static final int RPAREN = 40;
  public static final int LESSTHANEQUAL = 33;
  public static final int SEMICOLON = 46;
  public static final int NOT = 24;
  public static final int AND = 25;
  public static final int IN = 37;
  public static final int LESSTHAN = 32;
  public static final int OR = 26;
  public static final int TDEF = 18;
  public static final int COMMA = 48;
  public static final int RAT = 55;
  public static final int LOOP = 10;
  public static final int PLUS = 27;
  public static final int ASSIGN = 36;
  public static final int MAIN = 23;
  public static final int IF = 12;
  public static final int ID = 58;
  public static final int DOT = 49;
  public static final int EOF = 0;
  public static final int RETURN = 22;
  public static final int EQUAL = 34;
  public static final int TRUE = 51;
  public static final int error = 1;
  public static final int ANY_TYPE = 8;
  public static final int NULL = 50;
  public static final int SEC_TYPE = 9;
  public static final int INT_TYPE = 3;
  public static final int BREAK = 16;
  public static final int FDEF = 17;
  public static final int LBRACK = 41;
  public static final int COLON = 45;
  public static final int ENDIF = 15;
  public static final int LBRACE = 43;
  public static final int ELSE = 14;
  public static final int RBRACK = 42;
  public static final int READ = 20;
  public static final int FLOAT = 56;
  public static final int SEQ_TYPE = 7;
  public static final int RBRACE = 44;
  public static final int THEN = 13;
  public static final int MULTI = 29;
  public static final int STRING = 57;
  public static final int ALIAS = 19;
  public static final int FALSE = 52;
  public static final int FLOAT_TYPE = 5;
  public static final int PRINT = 21;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "BOOL_TYPE",
  "INT_TYPE",
  "RAT_TYPE",
  "FLOAT_TYPE",
  "CHAR_TYPE",
  "SEQ_TYPE",
  "ANY_TYPE",
  "SEC_TYPE",
  "LOOP",
  "POOL",
  "IF",
  "THEN",
  "ELSE",
  "ENDIF",
  "BREAK",
  "FDEF",
  "TDEF",
  "ALIAS",
  "READ",
  "PRINT",
  "RETURN",
  "MAIN",
  "NOT",
  "AND",
  "OR",
  "PLUS",
  "MINUS",
  "MULTI",
  "DIVIDE",
  "POWER",
  "LESSTHAN",
  "LESSTHANEQUAL",
  "EQUAL",
  "NOTEQUAL",
  "ASSIGN",
  "IN",
  "CONCAT",
  "LPAREN",
  "RPAREN",
  "LBRACK",
  "RBRACK",
  "LBRACE",
  "RBRACE",
  "COLON",
  "SEMICOLON",
  "GREATERTHAN",
  "COMMA",
  "DOT",
  "NULL",
  "TRUE",
  "FALSE",
  "CHAR",
  "INT",
  "RAT",
  "FLOAT",
  "STRING",
  "ID"
  };
}

